pipeline:
  build:
    image: itiut/gcc-criterion
    commands:
      - apt-get update
      - apt-get install -y bc git tar      
      - git clone http://projects.nwmqpa.com/nwmqpa/bistro-matics-tests.git tests
      - make buildlib
      - cd tests
      - make working
      - ./units
      - make coverage
      - git config remote.origin.url http://$GIT_USERNAME:$GIT_PASSWORD@projects.nwmqpa.com/nwmqpa/bistro-matics-tests.git
      - git config --global user.email "$GIT_EMAIL"
      - git add coverage_report.tar
      - git commit -a -m "Made coverage for $(git -C .. log | head -n 1)"
      - git push origin
    secrets: [ git_email, git_username, git_password ]
  telegram:
    image: appleboy/drone-telegram
    token: 459383341:AAEEQgfMOempl46rOebwt4NFF8taV40XQXk
    to: nwmqpa
    message: >
      {{#success build.status}}
        build {{build.commit}} from {{build.author}} succeeded. Good job.
      {{else}}
        build {{build.commit}} from {{build.author}} failed. Fix me please.
      {{/success}}
