pipeline:
  build:
    image: itiut/gcc-criterion
    commands:
      - apt-get update
      - apt-get install -y bc git tar
      - git clone http://projects.nwmqpa.com/nwmqpa/bistro-matics-tests.git tests
      - make buildlib
      - cd tests
      - make -C working
      - ./units
      - make -C coverage
      - git commit -a -m "Made coverage for build #{{build.number}}"
      - git push origin
pipeline:
  telegram:
    image: appleboy/drone-telegram
    token: 459383341:AAEEQgfMOempl46rOebwt4NFF8taV40XQXk
    to: nwmqpa
    message: >
      {{#success build.status}}
        build {{build.commit}} from {{build.author}} succeeded. Good job.
      {{else}}
        build {{build.commit}} from {{build.author}} failed. Fix me please.
      {{/success}}
