pipeline:
  build:
    image: itiut/gcc-criterion
    commands:
      - apt-get install -y bc
      - make buildlib
      - make -C tests working
      - ./tests/units
      - make -C tests crash
      - time ./tests/units