##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## Makefile that call the Makefile of each operator
##

all:
	make -C add/
	make -C sub/
	make -C mul/

clean:
	make -C add/ clean
	make -C sub/ clean
	make -C mul/ clean

fclean:
	make -C add/ fclean
	make -C sub/ fclean
	make -C mul/ fclean

re:
	make -C add/ re
	make -C sub/ re
	make -C mul/ re
